name: Check if there is conflicts and send mail
on:
  pull_request_target:
    types:
      - opened
env:
  pr_url: ${{ github.event.pull_request.url }}
jobs:
  check_PR:
    runs-on: ubuntu-latest
    steps:
      - name: check the conflicts
        run: echo '${{ env.pr_url }}'
      - name: Get the mergeable value for the pr_url
        run: | 
             echo "mergeable=$(curl -L  -H "Accept: application/vnd.github+json" -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "X-GitHub-Api-Version: 2022-11-28" '${{ env.pr_url }}' | jq '.mergeable')" >> $GITHUB_ENV

      - name: check the conflicts
        run: echo '${{ env.mergeable }}'
