name: Check if there is conflicts and send mail
on:
  pull_request_target:
    types:
      - opened
env:
  pr_url: ${{ github.event.pull_request.url }}
jobs:
  check_PR:
    runs-on: ubuntu-latest
    steps:
      - name: check the conflicts
        run: echo '${{ env.pr_url }}'
      - name: Get the mergeable value for the pr_url
        run: | 
             echo "mergeable=$(curl -L  -H "Accept: application/vnd.github+json" -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "X-GitHub-Api-Version: 2022-11-28" '${{ env.pr_url }}' | jq '.mergeable')" >> $GITHUB_ENV
      - name: send mail if mergeable
        if: ${{ ! startsWith( env.mergeable, 'false' )}}
        uses: dawidd6/action-send-mail@v3
        with:
            # Required mail server address if not connection_url:
            server_address: smtp.freesmtpservers.com
            # Server port, default 25:
            server_port: 25
            # Optional whether this connection use TLS (default is true if server_port is 465)
            secure: false
            # Required mail subject:
            subject: You have Mergable PR
            # Required recipients' addresses:
            to: adel@test.com
            from: check_rb@actions.com
            body: You have PR to approve '${{ env.pr_url }}'

      - name: send mail if not mergeable
        if: ${{ startsWith( env.mergeable, 'false' )}}
        uses: dawidd6/action-send-mail@v3
        with:
            # Required mail server address if not connection_url:
            server_address: smtp.freesmtpservers.com
            # Server port, default 25:
            server_port: 25
            # Optional whether this connection use TLS (default is true if server_port is 465)
            secure: false
            # Required mail subject:
            subject: You have not Mergable PR
            # Required recipients' addresses:
            to: adel@test.com
            from: check_rb@actions.com
            body: You have PR that isn't mergeable '${{ env.pr_url }}'